// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Multiply

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture


struct VecMatPair{
    float3 pos;
    float3 addition;
};

RWStructuredBuffer<VecMatPair> dataBuffer;

[numthreads(16,1,1)]
void Multiply (uint3 id : SV_DispatchThreadID)
{
    dataBuffer[id.x].pos += dataBuffer[id.x].addition; 
}
